#!/usr/bin/env python3

from os import makedirs, listdir
from os.path import dirname

from jinja2 import Environment, FileSystemLoader

with open("../settings.gradle.kts", "r") as f:
    for line in f.readlines():
        if line.startswith("    \"fabric:"):
            current_version = line.split(":")[1].split("\"")[0]
            break

print(f"version: {current_version}")
output_dir = f"./{current_version}/build/generatedSrc"
input_dir = f"./src/template/java"

env = Environment(
    loader=FileSystemLoader(input_dir),
    autoescape=False,
    keep_trailing_newline=True,
)

header = """// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOMATICALLY GENERATED
// INSTEAD, EDIT THE TEMPLATES
"""
header = header + "\n" * 30 + header

def convert_version_to_int(version):
    version_split = version.split(".")
    if len(version_split) < 3:
        version_split.append("0")
    major = version_split[0]
    minor = version_split[1].rjust(2, "0")
    patch = version_split[2].rjust(2, "0")
    return int(major + minor + patch)

current_version_as_var = "mc_" + current_version.replace(".", "_")
current_version = convert_version_to_int(current_version)
print(f"version as int: {current_version} (variable: {current_version_as_var})")

version_variables = {}
for version in listdir("."):
    if not version.startswith("1."):
        continue
    version_as_var = "mc_" + version.replace(".", "_")
    version_variables[version_as_var] = convert_version_to_int(version)

# for key, val in version_variables.items():
#     print(f"{key} = {val}")

for template_path in env.list_templates():
    template = env.get_template(template_path)
    output_path = output_dir + "/" + template_path
    makedirs(dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(header + template.render(minecraft_version=current_version, **version_variables).replace("//#", ""))
