#!/usr/bin/env python3

from os import makedirs
from os.path import dirname

from jinja2 import Environment, FileSystemLoader

with open("../settings.gradle.kts", "r") as f:
    for line in f.readlines():
        if line.startswith("    \"fabric:"):
            current_version = line.split(":")[1].split("\"")[0]
            break

print(f"version: {current_version}")
output_dir = f"./{current_version}/build/generatedSrc"
input_dir = f"./src/template/java"

env = Environment(
    loader=FileSystemLoader(input_dir),
    autoescape=False,
    keep_trailing_newline=True,
)

header = """// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOMATICALLY GENERATED
// INSTEAD, EDIT THE TEMPLATES
"""
header = header + "\n" * 30 + header

current_version_split = current_version.split(".")
if len(current_version_split) < 3:
    current_version_split.append("0")
major = current_version_split[0]
minor = current_version_split[1].rjust(2, "0")
patch = current_version_split[2].rjust(2, "0")
current_version = int(major + minor + patch)
print(f"version as int: {current_version} (with underscores: {major}_{minor}_{patch})")

for template_path in env.list_templates():
    template = env.get_template(template_path)
    output_path = output_dir + "/" + template_path
    makedirs(dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(header + template.render(minecraft_version=current_version).replace("//#", ""))
