// GENERATED BY generate_version_ranges.py - DO NOT EDIT BY HAND
// Make sure to update the GitHub Actions workflow if this changes
val fabricVersionRanges = mapOf(
    "1.16.5" to listOf("1.16.5", "1.18.2"),
    "1.19.2" to listOf("1.19.2", "1.20", "1.20.1", "1.20.2", "1.20.3", "1.20.4", "1.20.5", "1.20.6", "1.21", "1.21.1"),
    "1.21.2" to listOf("1.21.2", "1.21.3", "1.21.4"),
    "1.21.5" to listOf("1.21.5", "1.21.6", "1.21.7", "1.21.8", "1.21.9", "1.21.10"),
    "1.21.11" to listOf("1.21.11"),
    "26.1" to listOf("26.1", "26.1.1", "26.1.2", "26.2"),
)
