modLoader = "javafml"
loaderVersion = "*"
license = "MIT"
issueTrackerURL = "https://github.com/amsam0/voicechat-discord/issues"

[[mods]]
modId = "voicechat_discord"
version = "${modVersion}"
displayName = "Simple Voice Chat Discord Bridge"
displayURL = "https://modrinth.com/mod/simple-voice-chat-discord-bridge"
logoFile = "icon.png"
authors = "amsam0, Totobird"
description = '''A mod to make a bridge between Simple Voice Chat and Discord to allow for players without Simple Voice Chat installed on their client to hear and speak.'''

[[dependencies.voicechat_discord]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.voicechat_discord]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraftVersion}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.voicechat_discord]]
modId = "voicechat"
type = "required"
versionRange = "[${minecraftVersion}-${voicechatApiVersion},)"
ordering = "AFTER"
side = "BOTH"
