name: Build
run-name: ${{ inputs.type }} build

on:
  workflow_dispatch:
    inputs:
      type:
        description: Type
        required: true
        type: choice
        options:
        - nightly
        - release
        default: nightly

jobs:
  natives:
    concurrency:
      group: ${{ github.ref }}-${{ matrix.os }}-${{ matrix.arch }}
      cancel-in-progress: true

    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
        arch: [aarch64, x86_64, i686]
        exclude:
          - os: macos-latest
            arch: i686
          - os: windows-latest
            arch: aarch64
          - os: windows-latest
            arch: i686
        include:
          # OS specific keys
          - os: ubuntu-22.04
            triple: unknown-linux-gnu
            filename: libvoicechat_discord.so
            pre-install: sudo apt-get update -y #&& apt-get install -y curl
            #container: debian:buster
          - os: macos-latest
            triple: apple-darwin
            filename: libvoicechat_discord.dylib
          - os: windows-latest
            triple: pc-windows-gnu
            filename: voicechat_discord.dll

          # OS and arch specific keys
          - os: ubuntu-22.04
            arch: aarch64
            install: sudo apt-get install -y gcc-aarch64-linux-gnu
          - os: ubuntu-22.04
            arch: i686
            install: sudo apt-get install -y gcc-i686-linux-gnu

    runs-on: ${{ matrix.os }}
    #container:
    #  image: ${{ matrix.container }}
    steps:
      - name: Checkout GitLab repository
        run: git clone https://gitlab.com/amsam0/voicechat-discord.git .

      - name: git log
        run: git log

      - name: Log source hash (Unix)
        if: runner.os != 'Windows'
        run: find . -type f -exec sha256sum {} \;

      - name: Log source hash (Windows)
        if: runner.os == 'Windows'
        run: Get-ChildItem -Recurse -File | %{ Get-FileHash $_.FullName }

      - name: Upload source
        uses: actions/upload-artifact@v4
        with:
          name: source-${{ matrix.arch }}-${{ matrix.triple }}
          path: .
          if-no-files-found: error
          include-hidden-files: true

      - name: Cargo cache
        if: ${{ inputs.type == 'nightly' }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ matrix.arch }}-${{ matrix.triple }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Pre-package installation
        if: ${{ matrix.pre-install }}
        run: ${{ matrix.pre-install }}

      - name: Install packages
        if: ${{ matrix.install }}
        run: ${{ matrix.install }}

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        if: ${{ contains(matrix.os, 'macos') }}
        with:
          xcode-version: latest-stable

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.arch }}-${{ matrix.triple }}

      - name: Build ${{ matrix.arch }}-${{ matrix.triple }}
        run: cargo build --target ${{ matrix.arch }}-${{ matrix.triple }} --release
        working-directory: core

      - name: Upload ${{ matrix.filename }}
        uses: actions/upload-artifact@v4
        with:
          name: natives-${{ matrix.arch }}-${{ matrix.triple }}
          path: core/target/${{ matrix.arch }}-${{ matrix.triple }}/release/${{ matrix.filename }}
          if-no-files-found: error

  build:
    concurrency:
      group: ${{ github.ref }}-${{ matrix.platform }}-${{ matrix.version }}
      cancel-in-progress: true

    strategy:
      matrix:
        platform: [fabric]
        version: [1.19.2, 1.20.1, 1.21.1, 1.21.4, 1.21.5, 1.21.8, 1.21.9, 1.21.10]
        include:
          # We don't want paper to map to all the versions
          - platform: paper

    runs-on: ubuntu-22.04
    needs: [natives]
    steps:
      - name: Checkout GitLab repository
        run: git clone https://gitlab.com/amsam0/voicechat-discord.git .

      - name: git log
        run: git log

      - name: Log source hash (Unix)
        if: runner.os != 'Windows'
        run: find . -type f -exec sha256sum {} \;

      - name: Log source hash (Windows)
        if: runner.os == 'Windows'
        run: Get-ChildItem -Recurse -File | %{ Get-FileHash $_.FullName }

      - name: Upload source
        uses: actions/upload-artifact@v4
        with:
          name: source-${{ matrix.platform }}${{ matrix.version && '-' || '' }}${{ matrix.version }}
          path: .
          if-no-files-found: error
          include-hidden-files: true

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Download linux-aarch64
        uses: actions/download-artifact@v4
        with:
          name: natives-aarch64-unknown-linux-gnu
          path: core/src/main/resources/natives/linux-aarch64/

      - name: Download linux-x64
        uses: actions/download-artifact@v4
        with:
          name: natives-x86_64-unknown-linux-gnu
          path: core/src/main/resources/natives/linux-x64/

      - name: Download linux-x86
        uses: actions/download-artifact@v4
        with:
          name: natives-i686-unknown-linux-gnu
          path: core/src/main/resources/natives/linux-x86/

      - name: Download mac-aarch64
        uses: actions/download-artifact@v4
        with:
          name: natives-aarch64-apple-darwin
          path: core/src/main/resources/natives/mac-aarch64/

      - name: Download mac-x64
        uses: actions/download-artifact@v4
        with:
          name: natives-x86_64-apple-darwin
          path: core/src/main/resources/natives/mac-x64/

      - name: Download windows-x64
        uses: actions/download-artifact@v4
        with:
          name: natives-x86_64-pc-windows-gnu
          path: core/src/main/resources/natives/windows-x64/

      - name: Add nightly suffix to version
        run: sed -e '/pluginVersion = .*/s/"$/-nightly+${{ github.sha }}"/' -i buildSrc/src/main/kotlin/Properties.kt

      - name: Get version
        id: version
        run: echo "version=$(grep pluginVersion buildSrc/src/main/kotlin/Properties.kt | awk -F '"' '{print $2}')" >> $GITHUB_OUTPUT

      - name: Switch to version subproject
        if: ${{ matrix.version }}
        run: sed -E -e '/"${{ matrix.platform }}:/s/[^:]*",$/${{ matrix.version }}",/' -i settings.gradle.kts

      - name: Build subproject
        if: ${{ matrix.version }}
        run: ./gradlew :${{ matrix.platform }}:${{ matrix.version }}:build

      - name: Upload subproject artifact
        if: ${{ matrix.version }}
        uses: actions/upload-artifact@v4
        with:
          name: voicechat-discord-${{ matrix.platform }}-${{ matrix.version }}-nightly.jar
          path: ${{ matrix.platform }}/${{ matrix.version }}/build/libs/voicechat-discord-${{ matrix.platform }}-${{ matrix.version }}-${{ steps.version.outputs.version }}.jar

      - name: Build project
        if: ${{ !matrix.version }}
        run: ./gradlew :${{ matrix.platform }}:build

      - name: Upload project artifact
        if: ${{ !matrix.version }}
        uses: actions/upload-artifact@v4
        with:
          name: voicechat-discord-${{ matrix.platform }}-nightly.jar
          path: ${{ matrix.platform }}/build/libs/voicechat-discord-${{ matrix.platform }}-${{ steps.version.outputs.version }}.jar

  sync-body:
    if: ${{ inputs.type == 'release' }}

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    runs-on: ubuntu-22.04
    needs: [build]
    steps:
      - name: Checkout GitLab repository
        run: git clone https://gitlab.com/amsam0/voicechat-discord.git .

      - name: git log
        run: git log

      - name: Log source hash
        run: find . -type f -exec sha256sum {} \;

      - name: Upload source
        uses: actions/upload-artifact@v4
        with:
          name: source-sync-body
          path: .
          if-no-files-found: error
          include-hidden-files: true

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Sync body to modrinth
        run: ./gradlew :core:modrinthSyncBody
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
