name: Build
run-name: ${{ inputs.type }} build

on:
  workflow_dispatch:
    inputs:
      type:
        description: Type
        required: true
        type: choice
        options:
        - nightly
        - release
        default: nightly

jobs:
  natives:
    concurrency:
      group: ${{ github.ref }}-${{ matrix.os }}-${{ matrix.arch }}
      cancel-in-progress: true

    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
        arch: [aarch64, x86_64, i686]
        exclude:
          - os: macos-latest
            arch: i686
          - os: windows-latest
            arch: aarch64
          - os: windows-latest
            arch: i686
        include:
          # OS specific keys
          - os: ubuntu-22.04
            triple: unknown-linux-gnu
            filename: libvoicechat_discord.so
            build-command: zigbuild
            target-extra: .2.26
          - os: macos-latest
            triple: apple-darwin
            filename: libvoicechat_discord.dylib
            build-command: build
          - os: windows-latest
            triple: pc-windows-gnu
            filename: voicechat_discord.dll
            build-command: build

          # OS and arch specific keys
          - os: ubuntu-22.04
            arch: aarch64
            install: sudo apt-get update -y && sudo apt-get install -y gcc-aarch64-linux-gnu
          - os: ubuntu-22.04
            arch: i686
            install: sudo apt-get update -y && sudo apt-get install -y gcc-i686-linux-gnu

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout GitLab repository
        run: git clone https://gitlab.com/amsam0/voicechat-discord.git .

      - name: git log
        run: git log

      - name: '[unix] Log source hash'
        if: runner.os != 'Windows'
        run: find . -type f -exec sha256sum {} \;

      - name: '[windows] Log source hash'
        if: runner.os == 'Windows'
        run: Get-ChildItem -Recurse -File | %{ Get-FileHash $_.FullName }

      - name: Upload source
        uses: actions/upload-artifact@v4
        with:
          name: source-${{ matrix.arch }}-${{ matrix.triple }}
          path: .
          if-no-files-found: error
          include-hidden-files: true

      - name: '[nightly] Cargo cache'
        if: ${{ inputs.type == 'nightly' }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            **/target/
          key: cargo-${{ matrix.arch }}-${{ matrix.triple }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install packages
        if: ${{ matrix.install }}
        run: ${{ matrix.install }}

      - name: '[macos] Setup Xcode'
        uses: maxim-lobanov/setup-xcode@v1
        if: runner.os == 'macOS'
        with:
          xcode-version: latest-stable

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.arch }}-${{ matrix.triple }}

      - name: '[linux] Install zig'
        uses: mlugg/setup-zig@v2
        if: runner.os == 'Linux'

      - name: '[linux] Install cargo-zigbuild if needed'
        run: which cargo-zigbuild || cargo install --locked cargo-zigbuild
        if: runner.os == 'Linux'

      - name: Build ${{ matrix.arch }}-${{ matrix.triple }}${{ matrix.target-extra }}
        run: OPUS_STATIC=1 cargo ${{ matrix.build-command }} --target ${{ matrix.arch }}-${{ matrix.triple }}${{ matrix.target-extra }} --release
        working-directory: core

      - name: Upload ${{ matrix.filename }}
        uses: actions/upload-artifact@v4
        with:
          name: natives-${{ matrix.arch }}-${{ matrix.triple }}
          path: core/target/${{ matrix.arch }}-${{ matrix.triple }}/release/${{ matrix.filename }}
          if-no-files-found: error

  build:
    concurrency:
      group: ${{ github.ref }}-${{ matrix.platform }}-${{ matrix.version }}
      cancel-in-progress: true

    strategy:
      matrix:
        platform: [fabric]
        version: ["1.16.5", "1.18.2", "1.19.2", "1.20", "1.20.1", "1.20.2", "1.20.3", "1.20.4", "1.20.5", "1.20.6", "1.21", "1.21.1", "1.21.2", "1.21.3", "1.21.4", "1.21.5", "1.21.6", "1.21.7", "1.21.8", "1.21.9", "1.21.10"]
        include:
          # We don't want paper to map to all the versions
          - platform: paper

    runs-on: ubuntu-22.04
    needs: [natives]
    steps:
      - name: Checkout GitLab repository
        run: git clone https://gitlab.com/amsam0/voicechat-discord.git .

      - name: git log
        run: git log

      - name: '[unix] Log source hash'
        if: runner.os != 'Windows'
        run: find . -type f -exec sha256sum {} \;

      - name: '[windows] Log source hash'
        if: runner.os == 'Windows'
        run: Get-ChildItem -Recurse -File | %{ Get-FileHash $_.FullName }

      - name: Upload source
        uses: actions/upload-artifact@v4
        with:
          name: source-${{ matrix.platform }}${{ matrix.version && '-' || '' }}${{ matrix.version }}
          path: .
          if-no-files-found: error
          include-hidden-files: true

      - name: '[nightly] Gradle cache'
        uses: actions/cache@v4
        if: ${{ inputs.type == 'nightly' }}
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ matrix.platform }}${{ matrix.version && '-' || '' }}${{ matrix.version }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ matrix.platform }}${{ matrix.version && '-' || '' }}${{ matrix.version }}-

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Download linux-aarch64
        uses: actions/download-artifact@v4
        with:
          name: natives-aarch64-unknown-linux-gnu
          path: core/src/main/resources/natives/linux-aarch64/

      - name: Download linux-x64
        uses: actions/download-artifact@v4
        with:
          name: natives-x86_64-unknown-linux-gnu
          path: core/src/main/resources/natives/linux-x64/

      - name: Download linux-x86
        uses: actions/download-artifact@v4
        with:
          name: natives-i686-unknown-linux-gnu
          path: core/src/main/resources/natives/linux-x86/

      - name: Download mac-aarch64
        uses: actions/download-artifact@v4
        with:
          name: natives-aarch64-apple-darwin
          path: core/src/main/resources/natives/mac-aarch64/

      - name: Download mac-x64
        uses: actions/download-artifact@v4
        with:
          name: natives-x86_64-apple-darwin
          path: core/src/main/resources/natives/mac-x64/

      - name: Download windows-x64
        uses: actions/download-artifact@v4
        with:
          name: natives-x86_64-pc-windows-gnu
          path: core/src/main/resources/natives/windows-x64/

      - name: '[nightly] Get git SHA'
        if: ${{ inputs.type == 'nightly' }}
        id: sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: '[nightly] Add suffix to version'
        if: ${{ inputs.type == 'nightly' }}
        run: sed -e '/pluginVersion = .*/s/"$/-nightly+${{ steps.sha.outputs.sha }}"/' -i buildSrc/src/main/kotlin/Properties.kt

      - name: '[nightly] Get version'
        if: ${{ inputs.type == 'nightly' }}
        id: version
        run: echo "version=$(grep pluginVersion buildSrc/src/main/kotlin/Properties.kt | awk -F '"' '{print $2}')" >> $GITHUB_OUTPUT

      - name: Remove unnecessary platform subprojects
        run: sed -E -e '/(${{ matrix.platform }})|(core)/! s/.*",$//' -i settings.gradle.kts

      - name: '[versions] Switch to version subproject'
        if: ${{ matrix.version }}
        run: sed -E -e '/"${{ matrix.platform }}:/s/[^:]*",$/${{ matrix.version }}",/' -i settings.gradle.kts

      - name: '[nightly] Build project'
        if: ${{ inputs.type == 'nightly' }}
        run: ./gradlew :${{ matrix.platform }}${{ matrix.version && ':' || '' }}${{ matrix.version }}:build

      - name: '[nightly] Upload project artifact'
        if: ${{ inputs.type == 'nightly' }}
        uses: actions/upload-artifact@v4
        with:
          name: voicechat-discord-${{ matrix.platform }}${{ matrix.version && '-' || '' }}${{ matrix.version }}-nightly.jar
          path: ${{ matrix.platform }}${{ matrix.version && '/' || '' }}${{ matrix.version }}/build/libs/voicechat-discord-${{ matrix.platform }}${{ matrix.version && '-' || '' }}${{ matrix.version }}-${{ steps.version.outputs.version }}.jar

      - name: '[release] Build and publish project to Modrinth'
        if: ${{ inputs.type == 'release' }}
        run: ./gradlew :${{ matrix.platform }}${{ matrix.version && ':' || '' }}${{ matrix.version }}:modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

      - name: '[nightly] Stop Gradle daemon before creating cache'
        if: ${{ inputs.type == 'nightly' }}
        run: ./gradlew --stop

  sync-body:
    if: ${{ inputs.type == 'release' }}

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    runs-on: ubuntu-22.04
    needs: [build]
    steps:
      - name: Checkout GitLab repository
        run: git clone https://gitlab.com/amsam0/voicechat-discord.git .

      - name: git log
        run: git log

      - name: Log source hash
        run: find . -type f -exec sha256sum {} \;

      - name: Upload source
        uses: actions/upload-artifact@v4
        with:
          name: source-sync-body
          path: .
          if-no-files-found: error
          include-hidden-files: true

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Sync body to modrinth
        run: ./gradlew :core:modrinthSyncBody
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
