name: Build and upload nightly

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  natives:
    concurrency:
      group: ${{ github.ref }}-${{ matrix.os }}-${{ matrix.arch }}
      cancel-in-progress: true

    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
        arch: [aarch64, x86_64, i686]
        exclude:
          - os: macos-latest
            arch: i686
          - os: windows-latest
            arch: aarch64
          - os: windows-latest
            arch: i686
        include:
          # OS specific keys
          - os: ubuntu-22.04
            triple: unknown-linux-gnu
            filename: libvoicechat_discord.so
            pre-install: sudo apt-get update -y #&& apt-get install -y curl
            #container: debian:buster
          - os: macos-latest
            triple: apple-darwin
            filename: libvoicechat_discord.dylib
          - os: windows-latest
            triple: pc-windows-gnu
            filename: voicechat_discord.dll

          # OS and arch specific keys
          - os: ubuntu-22.04
            arch: aarch64
            install: sudo apt-get install -y gcc-aarch64-linux-gnu
          - os: ubuntu-22.04
            arch: i686
            install: sudo apt-get install -y gcc-i686-linux-gnu

    runs-on: ${{ matrix.os }}
    #container:
    #  image: ${{ matrix.container }}
    steps:
      - name: Checkout GitLab repository
        run: git clone https://gitlab.com/amsam0/voicechat-discord.git .

      - name: git log
        run: git log

      - name: Log source hash (Unix)
        if: runner.os != 'Windows'
        run: find . -type f -exec sha256sum {} \;

      - name: Log source hash (Windows)
        if: runner.os == 'Windows'
        run: Get-ChildItem -Recurse -File | %{ Get-FileHash $_.FullName }

      - name: Upload source
        uses: actions/upload-artifact@v4
        with:
          name: source-${{ matrix.arch }}-${{ matrix.triple }}
          path: .
          if-no-files-found: error
          include-hidden-files: true

      - name: Pre-package installation
        if: ${{ matrix.pre-install }}
        run: ${{ matrix.pre-install }}

      - name: Install packages
        if: ${{ matrix.install }}
        run: ${{ matrix.install }}

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        if: ${{ contains(matrix.os, 'macos') }}
        with:
          xcode-version: latest-stable

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.arch }}-${{ matrix.triple }}

      - name: Build ${{ matrix.arch }}-${{ matrix.triple }}
        run: cargo build --target ${{ matrix.arch }}-${{ matrix.triple }} --release
        working-directory: core

      - name: Upload ${{ matrix.filename }}
        uses: actions/upload-artifact@v4
        with:
          name: natives-${{ matrix.arch }}-${{ matrix.triple }}
          path: core/target/${{ matrix.arch }}-${{ matrix.triple }}/release/${{ matrix.filename }}
          if-no-files-found: error

  build:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-22.04
    needs: [natives]
    steps:
      - name: Checkout GitLab repository
        run: git clone https://gitlab.com/amsam0/voicechat-discord.git .

      - name: Log source hash (Unix)
        if: runner.os != 'Windows'
        run: |
          find . -type f -exec sha256sum {} \;
          git log

      - name: Log source hash (Windows)
        if: runner.os == 'Windows'
        # for some reason this fails with permission denied
        #run: Get-ChildItem -Recurse | %{ Get-FileHash $_.FullName }
        run: git log

      - name: Upload source
        uses: actions/upload-artifact@v4
        with:
          name: source-build
          path: .
          if-no-files-found: error
          include-hidden-files: true

      - name: Download linux-aarch64
        uses: actions/download-artifact@v4
        with:
          name: natives-aarch64-unknown-linux-gnu
          path: core/src/main/resources/natives/linux-aarch64/

      - name: Download linux-x64
        uses: actions/download-artifact@v4
        with:
          name: natives-x86_64-unknown-linux-gnu
          path: core/src/main/resources/natives/linux-x64/

      - name: Download linux-x86
        uses: actions/download-artifact@v4
        with:
          name: natives-i686-unknown-linux-gnu
          path: core/src/main/resources/natives/linux-x86/

      - name: Download mac-aarch64
        uses: actions/download-artifact@v4
        with:
          name: natives-aarch64-apple-darwin
          path: core/src/main/resources/natives/mac-aarch64/

      - name: Download mac-x64
        uses: actions/download-artifact@v4
        with:
          name: natives-x86_64-apple-darwin
          path: core/src/main/resources/natives/mac-x64/

      - name: Download windows-x64
        uses: actions/download-artifact@v4
        with:
          name: natives-x86_64-pc-windows-gnu
          path: core/src/main/resources/natives/windows-x64/

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Add nightly suffix to version
        run: sed -e '/pluginVersion = .*/s/"$/-nightly+${{ github.sha }}"/' -i buildSrc/src/main/kotlin/Properties.kt

      - name: Get version
        id: version
        run: echo "version=$(grep pluginVersion buildSrc/src/main/kotlin/Properties.kt | awk -F '"' '{print $2}')" >> $GITHUB_OUTPUT

      - name: Build paper
        run: ./gradlew :paper:build

      - name: Upload paper artifact
        uses: actions/upload-artifact@v4
        with:
          name: voicechat-discord-paper-nightly.jar
          path: paper/build/libs/voicechat-discord-paper-${{ steps.version.outputs.version }}.jar

      - name: Build fabric 1.19.2
        run: sed -E -e '/"fabric:/s/[^:]*",$/1.19.2",/' -i settings.gradle.kts && ./gradlew :fabric:1.19.2:build
      - name: Upload fabric 1.19.2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: voicechat-discord-fabric-1.19.2-nightly.jar
          path: fabric/1.19.2/build/libs/voicechat-discord-fabric-1.19.2-${{ steps.version.outputs.version }}.jar

      - name: Build fabric 1.20.1
        run: sed -E -e '/"fabric:/s/[^:]*",$/1.20.1",/' -i settings.gradle.kts && ./gradlew :fabric:1.20.1:build
      - name: Upload fabric 1.20.1 artifact
        uses: actions/upload-artifact@v4
        with:
          name: voicechat-discord-fabric-1.20.1-nightly.jar
          path: fabric/1.20.1/build/libs/voicechat-discord-fabric-1.20.1-${{ steps.version.outputs.version }}.jar

      - name: Build fabric 1.21.1
        run: sed -E -e '/"fabric:/s/[^:]*",$/1.21.1",/' -i settings.gradle.kts && ./gradlew :fabric:1.21.1:build
      - name: Upload fabric 1.21.1 artifact
        uses: actions/upload-artifact@v4
        with:
          name: voicechat-discord-fabric-1.21.1-nightly.jar
          path: fabric/1.21.1/build/libs/voicechat-discord-fabric-1.21.1-${{ steps.version.outputs.version }}.jar

      - name: Build fabric 1.21.4
        run: sed -E -e '/"fabric:/s/[^:]*",$/1.21.4",/' -i settings.gradle.kts && ./gradlew :fabric:1.21.4:build
      - name: Upload fabric 1.21.4 artifact
        uses: actions/upload-artifact@v4
        with:
          name: voicechat-discord-fabric-1.21.4-nightly.jar
          path: fabric/1.21.4/build/libs/voicechat-discord-fabric-1.21.4-${{ steps.version.outputs.version }}.jar

      - name: Build fabric 1.21.5
        run: sed -E -e '/"fabric:/s/[^:]*",$/1.21.5",/' -i settings.gradle.kts && ./gradlew :fabric:1.21.5:build
      - name: Upload fabric 1.21.5 artifact
        uses: actions/upload-artifact@v4
        with:
          name: voicechat-discord-fabric-1.21.5-nightly.jar
          path: fabric/1.21.5/build/libs/voicechat-discord-fabric-1.21.5-${{ steps.version.outputs.version }}.jar

      - name: Build fabric 1.21.8
        run: sed -E -e '/"fabric:/s/[^:]*",$/1.21.8",/' -i settings.gradle.kts && ./gradlew :fabric:1.21.8:build
      - name: Upload fabric 1.21.8 artifact
        uses: actions/upload-artifact@v4
        with:
          name: voicechat-discord-fabric-1.21.8-nightly.jar
          path: fabric/1.21.8/build/libs/voicechat-discord-fabric-1.21.8-${{ steps.version.outputs.version }}.jar
